esphome:
  name: $device_name
  on_boot:
    priority: 300
    then:
      lambda: |-
        WiFi.setPhyMode(WIFI_PHY_MODE_11B);

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $device_name
    password: !secret fallback_ap_password

debug: 
logger:
  level: DEBUG

web_server:
  port: 80

ota:
  safe_mode: true
  password: !secret ota_password