substitutions:
  device_name: esp-bed-occupancy

mqtt:
  <<: !include .mqtt.yaml

sensor:
  - platform: adc
    id: bed_occupancy_reading_raw
    pin: A0
    name: "Bed Occupancy Reading (Raw)"
    update_interval: 1s
    raw: true
    filters:
      - delta: '10%'

binary_sensor:
  - platform: template
    name: "Bed Occupancy"
    device_class: occupancy
    lambda: |-
      if (id(bed_occupancy_reading_raw).state > 25) {
        return true;
      } else {
        return false;
      }
    filters:
      - delayed_on: 5s
      - delayed_off: 30s

<<: !include .common.yaml