substitutions:
  device_name: esp-fountain

switch:
  - platform: gpio
    id: kitty_fountain
    name: Kitty Fountain
    pin:
      number: D5

binary_sensor:
  - platform: gpio
    name: Kitty Fountain Motion
    pin:
      number: D1
      mode:
        input: true
    on_press:
      then:
        - script.execute: turn_on_fountain

script:
  - id: turn_on_fountain
    mode: restart
    then:
      - switch.turn_on: kitty_fountain
      - delay: 60s
      - switch.turn_off: kitty_fountain

mqtt:
  <<: !include .mqtt.yaml
<<: !include .common.yaml